; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:client]
build_src_filter = +<Client_Wifi.cpp>
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

[env:server1]
build_src_filter = +<Server_Wifi.cpp>
upload_port = /dev/cu.usbserial-7
monitor_port = /dev/cu.usbserial-7
build_flags = -D WIFI_CHANNEL=1

[env:server2]
build_src_filter = +<Server_Wifi.cpp>
upload_port = /dev/cu.usbserial-8
monitor_port = /dev/cu.usbserial-8
build_flags = -D WIFI_CHANNEL=6

[env:server3]
build_src_filter = +<Server_Wifi.cpp>
upload_port = /dev/cu.usbserial-9
monitor_port = /dev/cu.usbserial-9
build_flags = -D WIFI_CHANNEL=11

[env:random]
build_src_filter = +<Random_Data.cpp>
; Set upload_port and monitor_port to match whichever ESP32 you are using for testing
upload_port = COM5
monitor_port = COM5